language: objective-c
osx_image: xcode8
xcode_project: TOCropViewControllerExample.xcodeproj
xcode_scheme: TOCropViewControllerTests
script: xcodebuild -verbose -scheme TOCropViewControllerTests -sdk iphonesimulator -destination "name=iPhone SE" test
